'use client';
import { useActionState } from 'react';
import Link from 'next/link';
import type { Student } from '@prisma/client';
import { saveStudent } from './actions';
export default function StudentForm({ student }: { student?: Student }) {
  const [state, action, pending] = useActionState(saveStudent.bind(null, student?.id ?? null), {});
  const fields = [{ name: 'studentCode', label: 'รหัสนักศึกษา', placeholder: 'เช่น 673450207-3', max: 30 }, { name: 'name', label: 'ชื่อ-นามสกุล', placeholder: 'กรอกชื่อและนามสกุล', max: 120 }, { name: 'email', label: 'Email (ไม่บังคับ)', placeholder: 'student@example.com', max: 254 }, { name: 'major', label: 'สาขา', placeholder: 'เช่น เทคโนโลยีสารสนเทศ', max: 100 }] as const;
  return <form action={action} className="panel form-panel"><h2>ข้อมูลนักศึกษา</h2><p className="muted mt-2 mb-7 text-sm">กรอกข้อมูลให้ครบถ้วน อีเมลสามารถเว้นว่างได้</p>{state.error && <p className="error-box" role="alert">{state.error}</p>}<div className="form-grid">{fields.map(f => <div key={f.name}><label htmlFor={f.name}>{f.label}{f.name !== 'email' && <span className="required"> *</span>}</label><input id={f.name} name={f.name} type={f.name === 'email' ? 'email' : 'text'} required={f.name !== 'email'} maxLength={f.max} defaultValue={state.values?.[f.name] ?? student?.[f.name] ?? ''} placeholder={f.placeholder} aria-invalid={!!state.fields?.[f.name]} aria-describedby={`${f.name}-error`}/><p id={`${f.name}-error`} className="field-error">{state.fields?.[f.name]?.[0]}</p></div>)}<div><label htmlFor="year">ชั้นปี <span className="required">*</span></label><select id="year" name="year" defaultValue={state.values?.year ?? student?.year ?? 1}>{Array.from({length: 8}, (_, i) => <option key={i+1} value={i+1}>ชั้นปีที่ {i+1}</option>)}</select><p className="field-error">{state.fields?.year?.[0]}</p></div><div><label htmlFor="status">สถานะ <span className="required">*</span></label><select id="status" name="status" defaultValue={state.values?.status ?? String(student?.status ?? true)}><option value="true">กำลังศึกษา</option><option value="false">ไม่ใช้งาน</option></select><p className="field-error">{state.fields?.status?.[0]}</p></div></div><div className="form-actions"><Link className="button secondary" href="/">ยกเลิก</Link><button className="button primary" disabled={pending}>{pending ? 'กำลังบันทึก…' : student ? 'บันทึกการแก้ไข' : 'บันทึกนักศึกษา'}</button></div></form>;
}
